name: Hexo Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # node-version: [20.x, 22.x]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm ci
      
      - name: Configure SSH
        env:
          DEPLOY_KEY_PRIVATE: ${{ secrets.DEPLOY_KEY_PRIVATE }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY_PRIVATE" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Test SSH Connection
        run: |
          ssh-keygen -lf ~/.ssh/id_rsa
          ssh -T git@github.com 2>&1 | \
          grep -q "GitHub does not provide shell access"
      
      - name: Build Hexo Site
        run: hexo generate
      
      - name: Configure Git
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Taoran-01"
          git config --global user.email "taoran200905@163.com"
          git config --global init.defaultBranch main
          git remote set-url origin \
          https://x-access-token:$TOKEN@github.com/Taoran-01/Algo-X.git
      
      - name: Deploy Website
        run: hexo deploy
      
      - name: Clean Build Files
        run: hexo clean
